; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = C:\Users\xuigouchen\AppData\Local\Programs\Microsoft VS Code\.pio\cache

[env:esp32-s3-devkitc-1]
platform = espressif32 @6.12.0
framework = arduino
board = esp32-s3-devkitc-1
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
lib_ldf_mode = chain
lib_deps = 
	finani/ICM42688 @ 1.1.0
	pololu/VL53L0X @ 1.3.1
	adafruit/Adafruit BMP5xx Library @ ^1.0.0
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-O3
	-ffast-math
	-DCORE_DEBUG_LEVEL=0
	-fno-exceptions
build_src_flags = -fno-rtti
build_unflags = -fno-rtti
